### ISSUE TITLE
alignは廃止されています

### ISSUE THREAD

**Issue by fa0311** [ActiveTK/ActiveTKDotJP#1]
align 属性は廃止されたので使用しないでください

[コンテンツ区分要素#属性](https://developer.mozilla.org/ja/docs/Web/HTML/Element/div#%E5%B1%9E%E6%80%A7)

**Comment by fa0311** [comment]
completed ?

**Comment by ActiveTK** [comment]
いえ、修正はせずに「修正不要」という形で閉じさせて頂きます。
あくまでも趣味で運営しているようなウェブサイトであり、HTML5の順守も行っておりません。
また、本リポジトリはソースコードを公開する事を目的としておりますので、原則としてIssuesの利用は行わない方針となります。(バグの報告はお問い合わせフォームからお願い申し上げます)
今後も、実行時のエラーを伴うバグを省いて修正するつもりもございませんので、ご了承ください。

**Comment by fa0311** [comment]
それならcompletedでcloseするのは不適切では
規格に沿ったレンダリングエンジンを使用すればレンダリング時にエラーが発生すると思います
(シェア率は限りなく低いと思うがレンダリングエンジンの寡占を促進させたくないのであれば対応するべき)
それとIssuesは無効化できるのでそういう方針なら無効化するべき
